In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set()

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('1.02.+Multiple+linear+regression.csv')

In [4]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [5]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [6]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [7]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [8]:
reg.coef_ #Two coefficients, one from each b1,b2 : sat,rand 123

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

0.29603261264909486

Calculating the Adjusted R squared value

In [10]:
reg.score(x,y) #This returns the R squared value, however we require the Adjusted R SQUARE value since it accounts
                # for stepping on the r square value and account for the increased variables used 
                # We now have R^2

0.40668119528142843

Formula for Adjusted R square

$R^2_{adj,} = 1 - (1 - R^2)*\frac{n-1}{n-p-1}$

In [11]:
# n stands for number of observations
# p stands for number of predictors
x.shape
#(n,p)

(84, 2)

In [12]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1 - (1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

In [13]:
# Since our adj r2 is considerably lower than our r2, we understand that one or more predictors we have have used
# have little to no explanatory power

Feature selection - to understand which variable has little to no explanatory power in our regression

In [14]:
from sklearn.feature_selection import f_regression
f_regression(x,y)
#returns the fstatistic and p value of both variables respectively

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [15]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [16]:
p_values.round(3)

array([0.   , 0.676])

In [17]:
#We notice p value of SAT is approx 0 and for Rand 1,2,3 it is 0.676 which is greater than 0.05 and thus discarded

In [18]:
#F regression should be used cautiously as these univariate p-values are arrived from simple linear models
#They do not represent the interconnection of the features represented in multiple linear models
#It may be too simplistic for otherwise complex problems and thus must be used cautiously

Creating a summary table

In [19]:
reg_summary = pd.DataFrame(data=x.columns.values,columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [20]:
# Creating a column for the coefficients and displaying
reg_summary['Coefficients'] = reg.coef_
reg_summary['p - values'] = p_values
reg_summary

Features  Coefficients    p - values
0         SAT      0.001654  7.199518e-11
1  Rand 1,2,3     -0.008270  6.762914e-01

In [21]:
#We thus understand what to eliminate and what not to.